-- drop schema if exists CASCADE;
CrEaTe ScHeMa IF NOT EXISTS teachers;

-- This command will remove (drop) the table.
-- DROP TABLE analysis.teachers;

-- Listing 2-2: Creating a table named teachers with six columns
CREATE TABLE teachers.teachers (
    -- id bigserial
    id integer generated by default as identity primary key 
    , first_name varchar(25)
    , last_name varchar(50)
    , school varchar(50)
    , hire_date date
    , salary numeric
);



-- Listing 2-3 Inserting data into the teachers table
INSERT INTO teachers.teachers (first_name, last_name, school, hire_date, salary)
VALUES 
    ('Janet', 'Smith', 'F.D. Roosevelt HS', '2011-10-30', 36200)
    , ('Lee', 'Reynolds', 'F.D. Roosevelt HS', '1993-05-22', 65000)
    , ('Samuel', 'Cole', 'Myers Middle School', '2005-08-01', 43500)
    , ('Samantha', 'Bush', 'Myers Middle School', '2011-10-30', 36200)
    , ('Betty', 'Diaz', 'Myers Middle School', '2005-08-30', 43500)
    , ('Kathleen', 'Roush', 'F.D. Roosevelt HS', '2010-10-22', 38500)
;


--- SELECT * FROM teachers.teachers;

